version: "3.5"

services:
  rabbitmq:
    image: rabbitmq:3.8.13-management
    container_name: service-event
    environment:
      - RABBITMQ_DEFAULT_USER=aforo255
      - RABBITMQ_DEFAULT_PASS=aforo255
    ports:
    - 5672:5672
    - 15672:15672
    networks:
    - aforo255  
  consul:
    image: consul:1.9.10
    container_name: service-discovery
    restart: always
    ports:
    - 8500:8500
    networks:
    - aforo255
  fabio:
    image: fabiolb/fabio:1.5.15-go1.15.5
    container_name: service-balancer
    environment:
    - FABIO_REGISTRY_CONSUL_ADDR=service-discovery:8500
    ports:
    - 9998:9998
    - 9999:9999
    networks:
    - aforo255
    depends_on:
    - consul
  config:
    image: nacos/nacos-server:v2.0.3
    container_name: service-config 
    environment:
    - MODE=standalone
    ports:
    - 8848:8848
    networks:
    - aforo255

networks:
  aforo255:
    name: micro