version: "3.5"

services:
  mysql:
    image: mysql:8.0.26
    container_name: mysql-database
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=Aforo255#2019
    ports:
    - 3307:3306
    - 33061:33060
    networks:
    - aforo255
  sql:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    container_name: sql-database
    restart: always
    ports:
    - 1434:1433
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=Aforo255#2019
    networks:
    - aforo255
  postgres:
    image: postgres:alpine3.14
    container_name: postgres-database
    environment:
    - POSTGRES_PASSWORD=Aforo255#2019
    ports:
    - 5434:5432
    networks:
    - aforo255
  mongo:
    image: mongo:5.0.2
    container_name: mongo-database
    environment:
    - MONGO_INITDB_ROOT_USERNAME=aforo255
    - MONGO_INITDB_ROOT_PASSWORD=Aforo255#2019
    ports:
    - 27018:27017
    networks:
    - aforo255
  mariadb:
    image: mariadb:10.2.36
    container_name: maria-database
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=Aforo255#2019
    ports:
    - 3310:3306
    - 33070:33060
    networks:
    - aforo255

networks:
  aforo255:
    name: micro